pokt-network/pocket

- README.md
Dead license link, and it's not a `.md` file :).
> README: Fix dead link

- README.md
- docs/README.md
Updated README sections and added missing links.
> Updated readme sections and added link to the Pocket Network Protocol repo

- .github/workflows/main.yml
Update main pipeline to run tests once
> [Quick CI change] Run tests once

- .gitignore
- Makefile
- p2p/types/mocks/mocks.go
- shared/modules/mocks/mocks.go
This PR make sure that the module expected by P2P tests is present.
Fixes #381 
- Updated Makefile
- Added "dummy" package
- updated gitignore
- loki driver is installed automatically if necessary
> [P2P] Tests expect a mock package on a clean codebase - (Issue #381)

- p2p/CHANGELOG.md
- p2p/raintree/peers_manager.go
- persistence/actor.go
As reported, it seems that LocalNet stopped working properly.
- Fixes #401 
- The flow within `GetAllStakedActors()` was simply incorrect
> [Persistence] Bugfix: Height no longer increases in LocalNet

- consensus/doc/CHANGELOG.md
- consensus/types/proto/state_sync.proto
- persistence/docs/CHANGELOG.md
- shared/CHANGELOG.md
Follow up to @gokutheengineer's comments in  #444 since it was merged before the review was complete.
NA
- Update changelog comments
- Add comment to the top of `state_sync.proto`
- ...
> [Consensus] Added comment to the top of state_sync.proto

- docs/demos/iteration_3_end_to_end_tx.md
- docs/deps/README.md
- docs/development/FAQ.md
- docs/development/README.md
- docs/learning/README.md
- docs/releases/README.md
- docs/roadmap/README.md
> [Documentation] Fix typos

- runtime/docs/README.md
Fixes a broken link in the runtime readme.
No related issue.
- Add the HTTP protocol prefix to the 12 factor app link URL
> [Runtime] docs: fix broken link

- docs/roadmap/README.md
Updating the roadmap timelines to reflect current project resources.
NA
- Testnet delivery pushed back 2 months (May to July 2023)
- All other timelines pushed back accordingly
- "Last Updated" date updated to today 
- Fixed minor issue with "M4" (was not hyperlinked to Milestones)
> [Documentation] Update V1 Roadmap Timelines

- build/localnet/README.md
great job on the demo. just suggested some content updates, trying to tailor the recommendations to k8s newbies and streamline the docs to avoid having to open 4 new tabs just to run the apps.
> Nicer instructions for k8s newbies

- consensus/debugging.go
- consensus/doc/CHANGELOG.md
- consensus/module.go
- shared/CHANGELOG.md
- shared/modules/consensus_module.go
Moves ConsensusDebugModule interface to the debugging.go.
Fixes #536 
- Moved ConsensusDebugModule interface and its functions to the debugging.go
> Quick fix for consensus interface

- Makefile
Adds a `docker_wipe_volumes` make target to the repo to facilitate easier resetting of the docker compose localnet. An example use case would be resetting the database / persistence module.
My localnet became non-functional after updating the default port number. The cause seemed to be old service URLs in the database, which is persisted across localnet restarts via a volume.
- Add `docker_wipe_volumes` target which removes existing volumes which contain the string `pocket-v1`.
> chore: add docker_w1pe_volumes make target

- build/Dockerfile.debian.dev
- build/Dockerfile.debian.prod
- build/docs/CHANGELOG.md
Fixes container builds.
- Changed Dockerfile for image builds to include $HOME variable
> [CI] fix container builds

- docs/devlog/devlog3.md
- docs/devlog/devlog4.md
This PR aims at addressing the CI error:
https://github.com/pokt-network/pocket/actions/runs/4514741249/jobs/7951188400
No issue because...  XS👕
- Updated slug for devlog in wiki
> docs(wiki): ValueError: Duplicate wiki path: devlog/template

- reviewpad.yml
https://twitter.com/reviewpad/status/1638951034675404808
> Added default reviewpad.yml file

- .githooks/pre-commit
- .githooks/pre-receive
- docs/development/README.md
- internal/testutil/mockdns.go
- p2p/CHANGELOG.md
- p2p/module_raintree_test.go
- p2p/raintree/peers_manager_test.go
- p2p/utils_test.go
Factors out some common `mockdns` usage, including a "noop" logger to things down (`mockdns` is noisy IMO).
Fixes #609 
- Create `/internal` directory
- Add `/interal/testutil` pkg
- Refactor existing `mockdns` usage
1. `go build -o ./pokt-node ./app/pocket`
2. `nm ./pokt-node | grep prepareDNSResolverMock` should print nothing
If `prepareDNSResolverMock` was included in the build, it will be listed in the symbol table which we can print with `nm`. **Double-check the function names match, a typo could result in a false positive**. Additionally, one can build a test binary (`go test -c -o <output bin path> [-run <test func name>] <pkg>`) on a test/pig which is known to import a test util function and ensure that it is present in the symbol table, as a …
> [Testing] Add `/internal/testutil` pkg & refactor mockdns test code

- docs/roadmap/README.md
Adjusted testnet delivery date to 09/01/2023 to reflect results of Q1 development and Q2 planning. All other timelines updated in accordance.
NA
- Updated M4: CoS due date to 09/01/2023
- Updated M* due dates accordingly
> Update roadmap readme.md timelines

- .github/PULL_REQUEST_TEMPLATE.md
Updates the pull request template to include E2E test items in the Testing section checklist.
- Adds E2E test items to the Testing checklist in the pull request template
> [Docs] Updates pull request template to include E2E items in Testing checklist

- Makefile
- build/localnet/README.md
Improve makefile targets to avoid using `go test` caching and inform the user that LocalNet is necessary for E2E tests.
Relayed to #759
- Add `-count=1` to all test helpers in the `Makefile` to avoid leveraging the caching feature
- Inform the user that `make localnet_up` is needed in `make test_e2e` until #759 is addressed
> [Comment] Inform user that LocalNet is needed for E2E tests

- .github/PULL_REQUEST_TEMPLATE.md
Add `reviewpad:summary` to the description to auto-populate it using AI.
> Update PULL_REQUEST_TEMPLATE.md - summary

- .github/workflows/changelog-verify.yml
The changelog validation step wasn't testing the output for failure but instead was always exiting with status 0.
This pull request fixes a bug where changelog validation was not exiting properly on failure. The patch now correctly exits on failure.
N/A
- CI validate step exits with appropriate status
> [Tooling] fix: changelog validation exits properly on failure

- .github/workflows/main.yml
- build/localnet/cluster-manager/main.go
Cluster manager was not aware of new binary p1.
This pull request contains 4 patches which make several changes in the project. The first patch changes the binary name for cluster manager. The second patch uses a custom-runner. The fourth patch attempts to fix an issue with installing argo. The fifth patch fixes a misspelling in one of the shell commands.
- Change #1
- Change #2
- ...
> [ClusterManager] change client binary name in cluster manager

- .github/workflows/main.yml
Fix CI `go test` tags.
N/A
- add `-tags=test` to the CI `go test` command.
> fix: add test flag to CI go test cmd

- docs/devlog/devlog8.md
- docs/roadmap/README.md
- Added Iteration17 (i.e. Devlog)
- Add a qualifier to the timelines
> Add README for Devlog8 for iteration17

- shared/modules/doc/README.md
Referencing PR #842 as an example of how to add a new module
> [Documentation] Add IBC Module introduction as an example

- shared/modules/mocks/mocks.go
Add back `shared/modules/mocks/mocks.go` so `make develop_test` works out of the box.
This was the issue:
Which was a result of the following change in #868:
And the following validates that this fix works:
- `gco HEAD@{4} shared/modules/mocks/mocks.go`
> [BUG] Bring back shared/modules/mocks/mocks.go

- p2p/transport_encryption_test.go
- p2p/utils_test.go
This pull request adds missing gobuild tags to the test files `transport_encryption_test.go` and `utils_test.go`.
Fixes N/A
- Add gobuild test tags
> [P2P] chore: Fix P2P linter errors

- persistence/trees/module.go
- persistence/trees/trees.go
> [Temp] s/TreeStore/treeStore

- build/config/config.validator1.json
- ibc/store/provable_store_test.go
- runtime/manager_test.go
> Update servicer private key for config.validator1.json

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/development/CODE_GUIDELINES.md
- docs/development/CODE_REVIEW_GUIDELINES.md
- docs/development/README.md
- docs/learning/README.md
- Add GPokT to the main README
- Add a foundation "code guidelines" only containing examples of comments
- Add details on tending resolving comments and reviewing PRs
- Add resources related to trees
> [Documentation] Code review guidelines & learning resources
