- .github/workflows/main.yml
Only build images for main branch until we have remote developer environments, when the images from other branches will be useful.
> [Quick CI change]

- Makefile
This PR makes sure that mocks are cleared before rebuilding/testing the current branch
Fixes #369
- Makefile target to clean mocks
- Calling the new Makefile target where required
> [DX] Dangling mocks cause errors when building/testing a branch after switching from another - Issue #369

- .github/workflows/main.yml
As we're using `tee` to pipe results of the tests to stdout and to `test_results.json` we need to sanitize what actually gets into that file, because non-json text breaks actions that expect json (obviously).
> [Quick CI fix] sanitize json test results before triggering annotation action

- Makefile
- persistence/indexer/indexer_test.go
- persistence/validator.go
- runtime/defaults/defaults.go
- utility/test/actor_test.go
- utility/test/block_test.go
- utility/test/module_test.go
- utility/test/transaction_test.go
Fix a flaky unit test in the utility module and address a bit of tech debt in parallel.
Fixes #373
**Root cause of bug:**
- In `newTestingTransaction`, always make the recipient a random address. This avoids the situation where the `proposer` and the `recipient` are the same (unlike but possible) resulting in the balance being increment in two different ways.
**Code cleanup:**
- Change order of params in `getActorByAddr`
- Avoid a few places with redundant byte <> string conversions
- Move tests from `block_test.go` that belong in `actor_test.go`
- Use more semantic variable naming where appropriate
- Use the `getFirstActor` helper test function in a few places
- Remove incorrect comments
> [Utility] Fix flaky tests `TestUtilityContext_ApplyBlock` and `TestUtilityContext_EndBlock`

- .github/workflows/main.yml
Our repo utilizes shared github runners which are prone to bottleneck on interaction with other services due to shared IPs/subnets. This time we hit a limit on downloads per IP on github's own artifact store, but this can be bypassed when the token is provided.
> [Quick ci change] avoid github action protoc download throttling

- Makefile
- docs/development/FAQ.md
Fix errors with the `Makefile` by removing the `--build` flag from the incorrect position in the `client_start` command, and add the `rebuild_client_start` command as well.
Add a description of an issue relating to starting the LocalNet with SELinux and its solution to `docs/development/FAQ.md`. This will be useful when `make compose_and_watch` throw errors, these have also been included in the file..
No issue documentation update
- Add issue and solution to FAQ for SELinux blocking the docker container from accessing local files to start the LocalNet
- Remove the `--build` flag from the `client_start` command in the `Makefile` and add the `rebuild_client_start` command with the `--build` flag in the correct position
> [Docs] Add LocalNet issues and solutions to FAQ

- Makefile
Quick fix for #417 which was overriding the target for `client_start` rather than creating a new one for `rebuild_client_start`
> Fix target for `rebuild_client_start`

- docs/development/README.md
This adds documentation mentioning the p1 binary (Pocket CLI) and how to build it utilizing the newly created Makefile targets.
Fixes #366
- Created a  `Pocket Network CLI` section in the development README.md
> [Docs] Build Makefile for p1 CLI documentation

- docs/learning/README.md
Removes an empty bullet point line.
This change just removes a blank line following a bullet point that I noticed while reading.
No related issue.
- Deleted a stray bullet point at the end of an unordered list.
> [Docs] tidy learning readme

- .githooks/pre-push
- .github/workflows/changelog-verify.yml
Duplicates and modifies the existing pre-commit hook to create a pre-push hook. This pre-push hook compares the CHANGELOG dates against the date of the most recent commit which affects the respective CHANGELOG's module.
Fixes #456
- Derive pre-push hook from existing pre-commit which compares CHANGELOG version dates against the date of the last commit which affects the respective module, instead of the current date.
- Swap new pre-push hook out for pre-commit in changelog verification GitHub actions job.
> [Tooling] changelog date verification: compare against last relevant commit

- consensus/doc/CHANGELOG.md
- consensus/e2e_tests/utils_test.go
Help out future developers who may hit a "WorksOnMyMachine" situation related to the consensus testing framework (#462).
Related to #462
- Add a note on consensus test-related workaround related to #462
> [Consensus] Add a TODO for #462 in the test framework

- Makefile
The `docker_wipe` make target is quite a destructive action as it destroys **all** containers, images, and volumes in docker. This includes things unrelated to the pocket and requires the user to **re-download** any docker images they may require, which can be very time consuming. Additionally, there is the potential to **lose data** in the destruction of the volumes. I think it's especially important that we provide a sufficient warning as we're including its usage in [developer documentation](https://github.com/pokt-network/pocket/tree/main/docs/development#running-localnet).
No open issue.
- Add appropriately scary warning to the `docker_wipe` target via a new phony dependency
> [Tooling] chore: add destrictive warning to docker_w*pe target

- .githooks/pre-receive
Quick fix to remove `changed_module_files=$(git diff --name-only main..HEAD | grep -e "^$module" )` which the github workflow has issues with and replace it with `changed_module_files=($( printf '%s\n' "${BRANCH_CHANGED_FILES[@]}" | grep "${module}" ))` so as to remove the need for the awkward git command.
Fixes N/A
- Remove the `git diff --name-only main..HEAD` command with a bash alternative
> [TOOLING] Fix changelog verification for worklow to extract current date

- consensus/doc/CHANGELOG.md
- consensus/e2e_tests/hotstuff_test.go
- p2p/CHANGELOG.md
- p2p/raintree/peers_manager_test.go
- persistence/docs/CHANGELOG.md
- persistence/test/application_test.go
- persistence/test/fisherman_test.go
- persistence/test/module_test.go
- persistence/test/service_node_test.go
- persistence/test/setup_test.go
- persistence/test/validator_test.go
- utility/doc/CHANGELOG.md
- utility/test/account_test.go
- utility/test/actor_test.go
This PR fixes all the unit test functions in all modules where actual and expected values were misplaced in `require.Equal` check.
Fixes #241
- Changes in consensus module - Fix `TestHotstuff4Nodes1BlockHappyPath` misplacement of actual and expected values in `require.Equal`.
- Changes in p2p module - Updated `TestRainTreeAddrBookUtilsHandleUpdate` and `testRainTreeMessageTargets` to correct incorrect expected and actual value placements.
- Changes in persistence module - Fix unit tests - `TestGetAppPauseHeightIfExists`, `TestGetAppOutputAddress`, `TestGetFishermanStatus`, `TestGetFishermanPauseHeightIfExists`, `TestGetFishermanOutputAddress`, `TestPersistenceContextParallelReadWrite`, `TestGetServiceNodePauseHeightIfExists`, …
> Fix: unit tests in consensus, p2p and persistence modules

- README.md
- app/client/doc/CHANGELOG.md
- app/client/keybase/README.md
Following the merge of #459 the `app/client/cli/doc` directory has moved to `app/client/doc` this PR fixes the links in the README
Fixes N/A
- Fix links to app documentation
- Change CLI to APP in links
> [DOCS] Fix links to app module docs

- build/Dockerfile.debian.dev
- build/Dockerfile.debian.prod
- build/docs/CHANGELOG.md
Fix Tilt permissions issue
Main build is broken as seen [here](https://github.com/pokt-network/pocket/actions/runs/4116795739/jobs/7107384911#step:7:894).
- Add `ENV PATH $PATH:$HOME/.local/bin` to `dev` and `prod` images
> [BUG] Tilt - Update permissions to avoid using sudo

- .github/workflows/main.yml
This PR updated our Github workflow to return the full output of failed tests for easier debugging/troubleshooting.
It was raised by @bryanchriswhite here:
https://github.com/pokt-network/pocket/pull/534#issuecomment-1441480145
And also probably related:
- updated `jq` 🪄 to return all the rows that match a failed test
> [Tooling] Returning failed tests full output

- consensus/doc/CHANGELOG.md
- consensus/module.go
- consensus/pacemaker/module.go
- consensus/state_sync/module.go
- logger/docs/CHANGELOG.md
- logger/docs/README.md
- logger/module.go
- p2p/CHANGELOG.md
- p2p/module.go
- p2p/raintree/network.go
- p2p/stdnetwork/network.go
- persistence/context.go
- persistence/docs/CHANGELOG.md
- persistence/genesis.go
- persistence/module.go
- rpc/doc/CHANGELOG.md
- rpc/module.go
- shared/CHANGELOG.md
- shared/modules/logger_module.go
- state_machine/docs/CHANGELOG.md
- state_machine/module.go
- telemetry/CHANGELOG.md
- telemetry/prometheus_module.go
- utility/context.go
- utility/doc/CHANGELOG.md
- utility/module.go
- utility/module_test.go
Previously when setting up a new module according to the logger module readme, one encounters [`hugeParam` linter error](https://golangci-lint.run/usage/linters/#gocritic) about the module's `logger` field.
- Update the logger module interface to use logger pointers instead of values
- Update logger value references with pointers
- Update README
> [Logger] Replace logger values with pointers

- libp2p/docs/CHANGELOG.md
- libp2p/module.go
- libp2p/protocol/protocol.go
- p2p/CHANGELOG.md
- p2p/module.go
This is another of a series of PRs split out from https://github.com/pokt-network/pocket/pull/500. Here we add a new `modules.P2PModule` implementation which utilizes the `typesP2P.Network` implementation which was added in #540. It will be utilized together with the config changes introduced by #535 in forthcoming changes to the node and debug CLI.
#347 
- Added a new `modules.P2PModule` implementation to the `libp2p` module directory
> [Libp2p] Add Libp2p module (part 4)

- app/client/cli/debug.go
- app/client/doc/CHANGELOG.md
- shared/CHANGELOG.md
- shared/node.go
This is another (last, probably) in a series of PRs split out from https://github.com/pokt-network/pocket/pull/500. Here we finally enable support for use of the new libp2p module (and dependent packages) by considering the config changes made in #535 in the node and debug CLI.
#347 
- Support libp2p module in node
- Support libp2p module in debug CLI
> [Libp2p] Plug it in (part 5)

- build/docs/CHANGELOG.md
- build/localnet/manifests/role-bindings.yaml
Allows cluster-manager to get `v1-localnet-validators-private-keys` secret.
Cluster manager complained about inability to access private keys secret when ran localnet from scratch.
- add `cluster-manager-account` service account to an existing binding
> add get secrets perms to cluster-manager-account service account

- shared/CHANGELOG.md
- shared/crypto/README.md
The Master key generation diagram and the Child key generation diagrams are in the wrong order in the SLIP documentation. This PR puts them the correct way around
Fixes N/A
- Reorder master key and child key generation diagrams
> [Documentation] Fix SLIP Master Key and Child Key diagrams to be in the correct order

- Makefile
- app/client/cli/cmd.go
- app/client/debug.go
- app/client/doc/CHANGELOG.md
- app/client/doc/README.md
- app/client/keybase/debug/keystore.go
- app/docs/CHANGELOG.md
- build/debug.go
- build/docs/CHANGELOG.md
- build/dummy.go
- build/localnet/Tiltfile
SImplifies the debug CLI tooling by embedding private-keys.yaml manifest into the CLI binary when the `debug` build tag is present. It removes some code from the debug keybase that detected if the CLI was running in kubernetes and would source the debug private keys from a configmap secret.
Fixes https://github.com/pokt-network/pocket/issues/525
See description.
> [CLI] add private keys embed to debug cli build

- go.mod
- go.sum
- libp2p/docs/CHANGELOG.md
- libp2p/network/url_conversion_test.go
This was a `TECHDEBT` item that became trivial to do as work progressed on another task which also required use of `mockdns` (#576).
Not related to any specific issue.
- Adds `mockdns` as a test dependency
- Mocks DNS resolution in `url_conversion_test.go`
- Adds regression tests to `url_conversion_test.go` for single- and multi-record DNS responses
> [P2P] test: URL conversion with mockdns

- .github/PULL_REQUEST_TEMPLATE.md
Help us bootstrap and subsequently maintain `godoc` comments in the codebase via our existing review process.
- Adds an item to the "Required Checklist" in the PR template
I'm extremely confident that we could automate these checks with the correct linter / config. At that point, we could remove this checklist item.
> chore: add `godoc` comment requirement

- libp2p/docs/CHANGELOG.md
- libp2p/network/network.go
- libp2p/network/network_test.go
- libp2p/network/url_conversion_test.go
- libp2p/network/utils_test.go
Due to circumstances and timing, @Olshansk's final review on #540 came in after merging. This PR implements improvements based on that review feedback.
Related to #347
- Correct libp2p module tests
- Improve libp2p code quality in response to post-merge review feedback
> [Libp2p] post-merge review improvements

- .github/workflows/changelog-verify.yml
This PR improves DevX by outputting the result of a changelog validation into the PR and requesting changes:
Once the check is successful, the automatically added review comments are dismissed
The commits of this PR are also included in #577 
None because developed in < 4h
- Updated changelog-verify.yaml to automatically review / dismiss changelog specific reviews
> [Tooling] Output changelog validation check into the PR automatically

- libp2p/docs/CHANGELOG.md
- libp2p/network/url_conversion.go
- libp2p/network/url_conversion_test.go
Fixes URL conversion utility returning invalid IPv6 URLs. Thanks again @0xBigBoss for the reminder about IPv6 URL formatting. :raised_hands: 
Related to but missing from #597 
- Wrap IPv6 address in square brackets as per [RFC3986 §3.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2)
> [P2P, Libp2p] fix: IPv6 conversion to valid URL

- consensus/doc/CHANGELOG.md
- consensus/hotstuff_leader.go
This PR addresses the bug reported in #631 
Fixes #631
- The apply logic was running indiscriminately and it has to run only if the leader is not preparing a new block
> [CONSENSUS] bugfix for: unable to send txs in localnet - Issue #631

- state_machine/docs/CHANGELOG.md
- state_machine/docs/README.md
Clarify that the `validators` instead of the `non-validators` enter `Consensus_Pacemaker` mode once they finish syncing in the state machine README file
Fixes N/A
- Clarify documentation
> [Documentation] Swap validator and non-validator triggers when finished synching

- .github/workflows/cr.yml
As seen on https://github.com/anc95/ChatGPT-CodeReview.
Triggered by adding the `gpt review` label so its not too expensive and doesn't run every time.
> Added ChatGPT-CodeReview workflow

- build/config/genesis.json
- build/docs/CHANGELOG.md
- build/localnet/manifests/configs.yaml
- persistence/account.go
- persistence/docs/CHANGELOG.md
- persistence/genesis.go
- persistence/state.go
- persistence/test/account_test.go
- persistence/test/module_test.go
- persistence/test/state_test.go
- runtime/docs/CHANGELOG.md
- runtime/manager_test.go
- runtime/test_artifacts/generator.go
- shared/CHANGELOG.md
- shared/core/types/pools.go
- shared/core/types/pools_test.go
- shared/modules/persistence_module.go
- utility/doc/CHANGELOG.md
- utility/types/error.go
- utility/unit_of_work/account.go
- utility/unit_of_work/account_test.go
- utility/unit_of_work/actor_test.go
- utility/unit_of_work/block.go
- utility/unit_of_work/transaction.go
- utility/unit_of_work/tx_message_handler.go
- utility/unit_of_work/validator.go
While working on #327 (KV Store PR) I realized that the scope was growing and it sounded sensible to create a specific PR with these fixes that I believe are gonna be needed regardless.
I didn't bother creating an issue since I guess this constitutes bug/techdebt even if it's necessary work for #327 if we move forward with the KV store approach.
- Fixed flag/params keying. It was using the hash of the value and not the name, making queries by name impossible
- Updated pools read/write functions to use a real address, not a string that is named address and obviously is not hexadecimal etc, etc.
- Added test to describe behaviour and catch future bugs (we already missed a pool that wasn't added to the FriendlyNames: `Pools_POOLS_FISHERMAN_STAKE`)
- …
> [Persistence][Utility] Pools Address hack removal + state accessor fix for params and flags

- reviewpad.yml
This pull request introduces a fix to the current reviewpad configuration. Reviewpad is currently failing because the YAML specification is incorrect.
N/A
- Update to `reviewpad.yml` used as input for [Reviewpad](https://github.com/reviewpad).
> [Infra] Update reviewpad configuration

- go.mod
- go.sum
- persistence/debug.go
- persistence/docs/CHANGELOG.md
- persistence/kvstore/kvstore.go
- persistence/state.go
This PR updates the dependencies to use `pocket-network/smt` (our fork) instead of `celestiaorg/smt` for the SMT. 
It is recommended to run the following:
```sh
rm -vfrd vendor/
go clean -modcache
make develop_start
```
Fixes N/A
- Update `go.mod` and the codebase to use the `pocket-network/smt` fork of celestia's SMT now it is archived
> [Dependencies] Update deps

- persistence/docs/CHANGELOG.md
- persistence/indexer/indexer.go
This PR fixes the `TxIndexer` so that it can index multiple transactions by sender and recipient instead of simply overwriting the previous transaction.
By adding the height and index of the index as a suffix to the key when storing the transaction bytes in the TxIndexer KVStore, we can now query all transactions sent or received by a specific address, through the TxIndexer.
Fixes N/A
- Index by Sender and Recipient with height and index suffixes
> [Peristence] Fix `TxIndexer` to index sender and recipient transactions with height and index suffixes

- .githooks/pre-commit
- .githooks/pre-receive
- docs/development/README.md
- internal/testutil/mockdns.go
- p2p/CHANGELOG.md
- p2p/module_raintree_test.go
- p2p/raintree/peers_manager_test.go
- p2p/utils_test.go
Factors out some common mockdns usage, including a "noop" logger to things down (mockdns is noisy IMO).
(Duplicate of #685 :roll_eyes:, I forgot to change the base branch before merging. As a result, the changes were squashed-merged into a different branch than main. Re-opening here, apologies for the extra noise. :pray::pray:)
Fixes #609
- Create `/internal` directory
- Add `/interal/testutil` pkg
- Refactor existing `mockdns` usage
1. `go build -o ./pokt-node ./app/pocket`
2. `nm ./pokt-node | grep prepareDNSResolverMock` should print nothing
If `prepareDNSResolverMock` was included in the build, it will be listed in the symbol table which we can print with `nm`. **Double-check the function names match, a typo could result in a false positive**. …
> [Testing (DUP)] Add /internal/testutil pkg & refactor mockdns test code

- Makefile
#658 changed how Postgres instances are handled and assigned to Validators in the LocalNet, which broke the Make target specified for grabbing a shell to the LocalNet database. This PR fixes the command to target the Postgres instance for validator-001 by default, since validator-001 used for other tasks by default.
- Changes `make localnet_db_cli` to target the Postgres instance that `validator001` uses.
> [Makefile] fixes the localnet_db_cli target

- Makefile
- build/localnet/Tiltfile
- build/localnet/manifests/cli-client.yaml
- e2e/docs/CHANGELOG.md
- e2e/tests/validator.go
This PR adjusts the names of the Kube  pod used in LocalNet to match its counterpart in DevNet for E2E testing and other cross-environment needs.
See [cli-client.yaml](https://github.com/pokt-network/protocol-infra/blob/main/charts/v1-network-base/templates/cli-client.yaml) for the exact manifest.
Related to #581 & #582 
- Renames the local deploy of the CLI client to match the [same name that DevNet deploys](https://github.com/pokt-network/protocol-infra/blob/main/charts/v1-network-base/templates/cli-client.yaml).
> [E2E] Standardize Kube pod name across DevNet and LocalNet

- app/client/cli/debug.go
- app/client/doc/CHANGELOG.md
- app/client/doc/README.md
- app/docs/CHANGELOG.md
This PR creates a sub-command in the debug CLI for every item in the interactive prompt list. This enables E2E tests to create more scenarios for testing and assertion.
Fixes #661 
- Builds out a list of subcommands from the list of prompt UI commands.
> [CLI] Debug subcommand extension

- consensus/doc/CHANGELOG.md
- consensus/e2e_tests/utils_test.go
- persistence/blockstore/block_store.go
- persistence/context.go
- persistence/docs/CHANGELOG.md
- persistence/kvstore/kvstore.go
- persistence/module.go
- shared/modules/doc/CHANGELOG.md
- shared/modules/persistence_module.go
Refactors BlockStore out into its own component on PersistenceContext and introduces the BlockStore interface.
Relates to #692 
- Refactors `blockStore` into its own package in `persistence/blockstore` instead of directly attaching a `KVStore` to the `PersistenceContext`.
- Creates the `BlockStore` interface
- Updates tests that previously used the KVStore mocks to use BlockStore mocks
> [Persistence] Refactors BlockStore

- README.md
- docs/development/README.md
- docs/learning/README.md
Minor additions to the learning and documentation guide that could help new contributors in onboarding to Pocket.
NA
- Explain all the GitHub labels we have that trigger custom build related actions
- Point to the GitHub Wiki in the onboarding guide
- Add links to all of the recent YouTube presentations
- Link to internal notion docs others may request access to
> [Documentation] Minor additions to learning & development guide

- e2e/tests/validator.go
In the validatorPod struct's RunCommand method, there has been a minor, yet significant change in the order of operations to ensure that the result field of the validatorPod struct correctly captures the full command result.
In the previous version of the method, the command result struct r was assigned to v.result before r.Stdout was populated with the command output. This meant that v.result always contained an empty string for its Stdout field, regardless of the command's actual output.
This has now been corrected by moving the assignment of r to v.result below the line where r.Stdout is populated. This ensures that the Stdout field of v.result correctly contains the command's output, and not an empty string.
This change is important because it provides accurate command output …
> Refactoring the assignment order of the RunCommand function in validatorPod

- app/client/keybase/keystore.go
- build/linters/errs.go
- consensus/hotstuff_replica.go
- persistence/gov.go
- persistence/kvstore/kvstore.go
- shared/crypto/ed25519.go
- shared/crypto/keys.go
Enhances the linter for inline error checks and alters existing error checks to be inline.
- Introduces new custom linter
- Changes existing code to be compliant with new linter rule
> [CI] Add inline error check linter

- p2p/CHANGELOG.md
- p2p/module.go
- p2p/module_raintree_test.go
- p2p/raintree/peerstore_utils.go
This pull request includes a cleanup and bug fix in module.go that utilizes the shared codec module when marshaling data sent over the wire, and it introduces a hacky workaround to cast a `uint32` to a `string` since it is being passed in as a `json.Number` through some codeflow. Additionally, the changelog has been updated to reflect these changes.
The error encountered is:
```bash
node1.consensus  | 9:11PM level=INFO broadcasting message to network PocketEnvelope={"content":{"type_url":"type.googleapis.com/utility.TxGossipMessage","value":"CtsBCl0KJ3R5cGUuZ29vZ2xlYXBpcy5jb20vdXRpbGl0eS5NZXNzYWdlU2VuZBIyChSZcEXn+ZM7GobRUrdy0giO+GK4dxIUmYBAWIreXuPWzSzOdGeuEMvjmJgaBDEwMDASFDExOTk1NjAzMDY1Mzk4NTAxNTM1GmQKIHuXVS389g22ddtxtHRZjRmsJu41Qe9N1GcGWwPkDEN8EkBMzGmDb7CQn1nbCnl6w9B1/mbzM8PVPnjRDGJMZFxo …
```
> [BUG] Int casting issue when sending tx

- consensus/doc/CHANGELOG.md
- consensus/e2e_tests/utils_test.go
- consensus/state_sync/server.go
- persistence/block.go
- persistence/blockstore/block_store.go
- persistence/context.go
- persistence/debug.go
- persistence/docs/CHANGELOG.md
- persistence/test/state_test.go
- rpc/doc/CHANGELOG.md
- rpc/handlers_query.go
This PR refactors the persistence module to create the BlockStore interface. In doing so, it stops higher level components from directly calling the KVStore and exposes a specialized GetBlock and StoreBlock function instead. These two will eventually be wrapped with savepoints and rollbacks logic to facilitate atomic commits to the block store.
Parts of #562
- Creates the BlockStore interface and replaces mocks to use it where possible
- Forces height and block serialization handling down into the BlockStore module, making it cleaner and easier to get any block from the bus.
> [Persistence] Refactors BlockStore Interface

- .github/workflows/main.yml
In the prepare code coverage report workflow job this actually corrupts the coverage report being uploaded to codecov resulting in a no usable upload error. This command (from my understanding) makes the coverage report readable for humans.
Fixes N/A
- Remove code coverage preparation step in workflow
- Explicitly state the coverage file to be uploaded to codecov
> Remove coverage prep stage as this corrupts the coverage report

- Makefile
Add missing `--build-tags` flag to the `go_lint` makefile target.
This pull request adds a `--build-tags` flag to the `go_lint` make target, allowing developers to run linters for specific build tags. The patch enables the test tag during the linting process.
N/A
- Added `--build-tags "test"` to `go_lint` makefile target
> chore: add `--build-tags` flag to `go_lint` make target

- build/docs/CHANGELOG.md
- build/localnet/Tiltfile
This pull request contains two patches. The first patch breaks the go test cache by adding `-count=1` to tilt e2e-test execution. The second patch updates the changelog to reflect the changes made.
N/A
- Add `-count=1` flag to tilt e2e test execution to break the go test cache
> [Tooling] chore: break tilt e2e test cache

- .gitguardian.yaml
- .gitignore
- Makefile
This pull request includes changes to add .gitguardian.yaml file to ignore secrets and gitignore patterns for ggshield. There are also updates to the Makefile to include new targets for ggshield to scan and ignore secrets, as well as an update to make the path relative in the .gitguardian.yaml file.
NA
- Added `ggshiled` helpers to scan and ignore secrets in the future
- Ignoring a secret that was introduced by #827 that was blocking main seen [here](https://github.com/pokt-network/pocket/pull/803/checks?check_run_id=14359233756)
- 
NA
> [General] Ignore false positive secret uncovered by `ggshield` on main

- docs/development/CODE_REVIEW_GUIDELINES.md
Adds recommended keywords NIT, TECHDEBT, and SOS for use during review to signal next steps for the author.
This pull request adds new code review keywords for `nits`, `techdebt`, and `show stoppers` to the `CODE_REVIEW_GUIDELINES.md` file. It also updates the formatting and provides additional guidelines for Pull Request approval.
Stacks on top of #773
- adds definitions for NIT, TECHDEBT, TECHDEBT(XXX), and SOS keywords for use in code review.
> [Docs] Add code review keywords for nits, techdebt, and show stoppers

- persistence/context.go
- persistence/docs/CHANGELOG.md
- persistence/module.go
- persistence/trees/module.go
- persistence/trees/trees.go
- shared/modules/persistence_module.go
- shared/modules/treestore_module.go
Loads the TreeStore from a proper module and allows it access to the bus.
Refactor related to #756
This PR is the sum of feedback from #808. 
- Makes the TreeStore component into a proper module.
- Removes the txIndexer from the Update method interface.
> [Persistence] Adds TreeStore Module

- go.mod
- persistence/kvstore/kvstore.go
- persistence/kvstore/kvstore_test.go
This PR introduces unit tests to cover the KVStore's functionality as well as updating the KVStore logic to use the Badger wrapper functions `update`, `view`, etc.
This fixes the issues around deleting keys from the KVStore.
Fixes N/A
- Update KVStore to use badger's wrapper functions
- Add KVStore unit tests
> [Persistence] Update KVStore to use Badger wrapper functions

- persistence/docs/CHANGELOG.md
- persistence/module.go
- persistence/trees/module.go
- persistence/trees/trees.go
- [Persistence] Adds a logger to TreeStore module
Enabled by changes introduced in #756 and #808
- Adds a logger to the tree store
> [Persistence] Adds TreeStore logger

- build/localnet/Tiltfile
if you ever wondered if we could have tab completions inside localnet fret no more! This PR adds it to the cli client pod so you don't have to.
I looked at adding it to the docker setup, but that's not using the binary.
Enjoy! 👩🏻‍💻
```
make localnet_up # of course
make localnet_shell
root@dev-cli-client-9f4579876-5pmn7:~# p1 <TAB>
```
> QOL: add bash completion for p1 to localnet client

- persistence/actor.go
An issue was discovered in the `GetActor` function defined in `actor.go`. Specifically, when the `actorType` input argument matches with `types.ValidatorActor.GetActorType()`, the `schema` variable is currently assigned as `types.FishermanActor`. This appears to be a typo or error, as logically `schema` should be assigned `types.ValidatorActor` in this case. This could potentially cause `GetActor` to behave unexpectedly when called with `types.ValidatorActor.GetActorType()` as it would process as if it were `types.FishermanActor.GetActorType()`.
This pull request corrects the `schema` assignment for `types.ValidatorActor.GetActorType()` from `types.FishermanActor` to `types.ValidatorActor`, thus aligning the function behavior with the expected logic.
> [Persistence][Bug] Fix Actor Schema Assignment for ValidatorActor in GetActor

- ibc/store/proofs_ics23.go
In `proofs_ics23.go`, the `createMembershipProof` and `createNonMembershipProof` functions call `tree.Prove(key)` and then pass the `proof` to the `convertSMPToExistenceProof` or `convertSMPToExclusionProof` functions without checking if `proof` is `nil`. This could lead to a panic due to a nil pointer dereference if `tree.Prove(key)` returns a `nil` proof.
This PR adds a check to verify if `proof` is `nil` before passing it to the `convertSMPToExistenceProof` or `convertSMPToExclusionProof` functions. If `proof` is `nil`, an error is returned.
Added nil check on `proof` in `createMembershipProof` and `createNonMembershipProof` functions in `proofs_ics23.go`.
> [IBC] Add nil check on proof for membership and non-membership proof creation

- .github/workflows/golangci-lint.yml
- .github/workflows/main.yml
- .golangci.yml
- Makefile
- app/client/cli/consensus.go
- p2p/config/config.go
- p2p/raintree/router.go
This pull request includes the following changes:
- Added a new file `.github/workflows/golangci-lint.yml` for golangci-lint workflow.
- Modified the `.github/workflows/main.yml` file by removing the `golangci-lint` job.
- Updated the `.golangci.yml` file to remove the `typecheck` linter.
- Updated the `Makefile` to add installation of `helm` and `tilt` as part of `install_cli_deps` task.
- Modified the `app/client/cli/consensus.go` file by adding an import statement.
- Modified the `p2p/config/config.go` file to return an error in the `IsValid()` method.
- Modified the `p2p/raintree/router.go` file by removing the unused import and variable.
Overall, this pull request adds a new golangci-lint workflow, updates some workflow files, makes changes to the Makefile, and modifies a few Go …
> [Bug] Fix CI linter errors

- charts/pocket/README.md
- charts/pocket/values.yaml
Turning off volumes on LocalNet makes it easier to provision nodes, as they no longer depend on Kubernetes volumes. The LocalNet nodes are ephemeral anyway, so we don't lose anything by doing that.
This pull request includes two patches. 
The first patch disables persistence of volumes on LocalNet by setting the `enabled` field to `false` in the `charts/pocket/values.yaml` file.
The second patch adds generated helm docs by updating the `charts/pocket/README.md` file. The `persistence.enabled` field is also set to `false` in this patch.
Overall, these patches disable the persistent volume claim feature and add documentation changes.
> disable persistance of volumes on LocalNet

- p2p/background/kad_discovery_baseline_test.go
- p2p/background/router_test.go
There were two tests which were expressing flaky behavior. In both cases the tests failed via panic, which is my hypothetical explanation for why nothing printed in the test failure output; I think that CI step is not sensitive to the panic failure mode output.
To reproduce and/or verify this change, use the `-count=X` and `-run` flags to run a specific test `X` number of times consecutively:
```bash
go test -count=10 -run Libp2pKademliaPeerDiscovery ./p2p/background
go test -count=10 -run BackgroundRouter_broadcast ./p2p/background
```
Wasn't calling `#Close()` on its libp2p `Host` or it's DHT. This has been added in a `t.Cleanup(...)`.
Was panicking when an unanticipated connection is made in the context of kademlia overlay network bootstrapping (which is effectively out of our …
> [P2P] Fix flaky P2P tests

- Makefile
This pull request adds a new target `trigger_ci` to the Makefile. The `trigger_ci` target triggers the CI pipeline by submitting an empty commit.
#900
- Add a make target called `trigger_ci` that pushes an empty commit
- `make trigger_ci`
> [Core] Add trigger_ci target that pushes an empty commit

- persistence/actor.go
- persistence/block.go
- persistence/test/actor_test.go
- persistence/trees/trees.go
- persistence/trees/trees_test.go
- rpc/utils.go
- rpc/v1/openapi.yaml
- shared/core/types/proto/block.proto
- shared/modules/persistence_module.go
- shared/modules/treestore_module.go
This pull request includes the following changes:
- Added a new function `GetTreeHashes` in the `trees.go` file.
- Added import statements in various files.
- Added functions and tests related to preparing and inserting blocks, getting validator set hashes, and hashing validator set.
- Added a test function `TestTreeStore_GetTreeHashes` in the `trees_test.go` file.
- Made changes to the `block.proto` file including updating the `BlockHeader` message, adding the `ValidatorSet` message, and adding the `ValidatorIdentity` message.
- Added a method `GetTreeHashes` in the `treestore_module.go` file.
- Made changes to the `openapi.yaml` file related to the "Block" schema.
- Added a new function `GetValidatorSet` in the `actor.go` file.
- Made changes to the `actor_test.go` file related to …
> [Persistence] Update block header

- docs/development/README.md
This pull request updates the README.md file in the "docs/development" directory. It includes changes to the pre-commit changelog verification and provides a note explaining that the verification has been disabled during the development of V1 in order to unblock development velocity. The patch also includes a link to more details about the change.
Fixes #<issue_number>
- Change #1
- Change #2
- ...
> [Docs] Update development docs to warn to not use the changelog hook

- ibc/ibc_handle_event_test.go
- ibc/module.go
- ibc/store/bulk_store_cache.go
- ibc/store/provable_store.go
- ibc/store/provable_store_test.go
- internal/testutil/ibc/mock.go
- shared/modules/ibc_store_module.go
This pull request renames the `FlushAllEntries` function to `FlushCachesToStore` in multiple files. The function is responsible for flushing the cache entries for all stores in the `bulkStoreCache` struct. The renaming is consistent across the affected files, including `ibc_handle_event_test.go`, `module.go`, `bulk_store_cache.go`, `provable_store.go`, `provable_store_test.go`, `mock.go`, and `ibc_store_module.go`. The patch also includes some code formatting changes.
Fixes https://github.com/pokt-network/pocket/pull/868/files#r1262167821
- Rename `FlushAllEntries` to `FlushCachesToStore`
- Rename `FlushEntries` to `FlushCache`
> [IBC] chore: Rename FlushAllEntries => FlushCachesToStore

- Makefile
- ibc/types/proofs.go
- ibc/types/proto/proofs.proto
This PR copies in the `cosmos/ics23` protobuf definition file into the IBC types directory.
Doing so allows the `protoc` compile to compile the protobuf definitions correctly such that they implement the `proto.Message` interface, as when compiled using the `gogoproto` fork used by cosmos they do not. This is to allow for the `ProofSpec` to be included in the light client `PocketClientState` message in #916. In this usecase the `ics23.SmtSpec` cannot be used directly due to the issues mention above.
This pull request includes the following changes:
- A newly added file containing the implementation of types and functions related to proofs in the ibc package. It includes conversion functions and a definition of a SmtSpec variable.
- Changes in the "proofs.proto" file, including the …
> [IBC] Clone `cosmos/ics23` protobuf definitions into IBC repo

- app/client/cli/node.go
Adds the first step of the CLI harness for save and load E2E testing. This PR is the first of a series and will be followed by additional PRs adding the actual sub-command logic and execution. 
`node` keyword was chosen contrary to #566 as per the Discussion in Discord.
Relates to a series of changes to address #566
- Adds the `node` sub-command to the app CLI.
> [Persistence] Adds `node` subcommand to CLI

- charts/pocket/README.md
- charts/pocket/values.yaml
This pull request includes two commits. 
The first commit enables the IBC module in the k8s validators. It adds new configurations for the IBC module and sets it to enabled. It also specifies the stores directory and the private key for the host. 
The second commit adds generated helm documentation to the pocket charts. It modifies the README.md file to include documentation for the configuration settings related to the IBC module.
Overall, these changes enable the IBC module in k8s validators and provide documentation for it in the helm charts.
Fixes N/A
- Enable IBC module in k8s validators
> [IBC] chore: enable IBC module in k8s validators

- ibc/ibc_msg_mempool_test.go
- persistence/block.go
- persistence/trees/trees.go
- persistence/trees/trees_test.go
- shared/modules/persistence_module.go
- shared/modules/treestore_module.go
- utility/transaction.go
- utility/transaction_test.go
This pull request includes the following changes:
1. In the `trees.go` file:
- Added a new method `Prove` that generates and verifies a proof against a tree name stored in the `TreeStore`.
- Updated the `GetTreeHashes` method to exclude the root tree from the map of tree names to their root hashes.
2. In the `treestore_module.go` file:
- Added a new method `Prove` that generates and verifies a proof against a tree with a matching name.
- No other changes have been made to the existing methods in the file.
3. In the `transaction_test.go` file:
- Modified the import statements to use different package names.
- Modified the test cases `TestHandleTransaction_ErrorAlreadyInMempool`, `TestHandleTransaction_ErrorAlreadyCommitted`, and `TestHandleTransaction_BasicValidation`.
- Modified the …
> [Utility] Use TreeStore as source of truth

- build/localnet/manifests/cli-client.yaml
- charts/pocket/README.md
- charts/pocket/templates/statefulset.yaml
- charts/pocket/values.yaml
This pull request includes three patches. 
Patch 1/3 enables the IBC module in k8s validators. It adds the "ibc" section to the values.yaml file and sets the "enabled" field to true. It also specifies the "stores_dir" path for IBC data and adds the "private_key" field for the IBC host, although it is marked as ignored.
Patch 2/3 enables validators and IBC Host creation. It modifies the cli-client.yaml and statefulset.yaml files, adding environment variables for the IBC host private key and enabling the validator and IBC modules.
Patch 3/3 adds generated helm docs. It updates the README.md file, removing the "ibc" section and updating the "validator" section with the "enabled" field.
Overall, these patches enable the IBC module, validators, and IBC host creation in the Pocket k8s chart, …
> [IBC] Enable validators and thus IBC host creation in K8s

- utility/doc/README.md
- utility/doc/TRUSTLESS_RELAY_VALIDATION.md
- utility/doc/trustless_relay_validation.md
Add diagrams to describe validations done on trustless relays. Part of work on #918 
Fixes #918 
- Add a new markdown file to show trustless relay validations.
> [Utility] Create trustless_relay_validation.md

- app/client/cli/debug.go
When running commands like `p1 dui TriggerNextView`, seems the program exits faster than the p2p module can broadcast. This PR introduces a magic number to give the p2p module _enough_ time to broadcast the debug messages when run as a subcommand.
This is working for my e2e testing for now.
> hack: 😴 sleep enough for cli debug subcommands to broadcast

- runtime/configs/proto/servicer_config.proto
- utility/module_enable_actors_test.go
- utility/servicer/module.go
- utility/servicer/module_test.go
This PR modifies servicer code to sign all the served relays. It also modified the servicer configuration to a) provide the required private key, and b) remove public key and address fields which are now driven from the private key.
Fixes #832 
- Updaed servicer config proto file.
- Updated servicer module
- Updated unit tests covering servicer module
> [Utility] servicer signs relays

- go.mod
- go.sum
This pull request updates the dependencies in the `go.mod` file and the `go.sum` file. It restores the origin `gocuke` dependency and updates it to version 0.6.3.
N/A (techdebt)
- Remove `replace` directive in go.mod for gocuke dependency
- Update gocuke dependency to v0.6.3 (latest release; includes our fork's changes)
> chore: restore origin gocuke and update
